### PR TITLE
feat/DEVSU-2459 make report signatures customizable

### PR DESCRIPTION
**Pull request by sshugsc**
[DEVSU-2459](https://www.bcgsc.ca/jira/browse/DEVSU-2459)
- add signature type to template view

Note: need to test with api branch [feature/DEVSU-2459-make-report-signatures-customizable](https://github.com/bcgsc/pori_ipr_api/tree/feature/DEVSU-2459-make-report-signatures-customizable)

### CODE REVIEW

**Review by elewis2 — CHANGES_REQUESTED** [review]
Signature selection looks good.

Changes to make: Only signatures that are in the template for this report type should appear in the report pages for signing or be displayed in the print views.

**Comment by elewis2** [comment]
Noting that I'm getting a "Cannot destructure property 'data' of 'image' as it is undefined." error when I try to see either print view for a rapid report while testing this. Maybe unrelated.

**Comment by bnguyen-bcgsc** [comment]
I think the right side margin/padding should be increased a tad to make the spacing more balanced, what do you think @kttkjl?

**Comment by sshugsc** [comment]
> Noting that I'm getting a "Cannot destructure property 'data' of 'image' as it is undefined." error when I try to see either print view for a rapid report while testing this. Maybe unrelated.

@bnguyen-bcgsc handled in https://github.com/bcgsc/pori_ipr_api/pull/388. Thanks!

**Comment by sshugsc** [comment]
> Changes to make: Only signatures that are in the template for this report type should appear in the report pages for signing or be displayed in the print views.

Resolved. need to test with api branch: [bugfix/DEVSU-2460](https://github.com/bcgsc/pori_ipr_api/tree/bugfix/DEVSU-2460-make-template-signaturetype--return-empty-array-when-get)

**Review by elewis2 — APPROVED** [review]

**Pull request merged**
