### PR TITLE
Release/v6.30.0

### PR DESCRIPTION
**Pull request by kttkjl**
### Release Notes - IPR - Version client v6.30.0

**Bugfixes**
[[DEVSU-2153](https://www.bcgsc.ca/jira/browse/DEVSU-2153)] - PDF genomic report sometimes missing sections
[[DEVSU-2256](https://www.bcgsc.ca/jira/browse/DEVSU-2256)] - Add toggle for allowNotifications
[[DEVSU-2265](https://www.bcgsc.ca/jira/browse/DEVSU-2265)] - Printed genomic report - issues with tables across two tables
[[DEVSU-2276](https://www.bcgsc.ca/jira/browse/DEVSU-2276)] - "no rows to show" cut off in expression correlation tables
[[DEVSU-2277](https://www.bcgsc.ca/jira/browse/DEVSU-2277)] - update 'do you want to stay logged in' box options
[[DEVSU-2287](https://www.bcgsc.ca/jira/browse/DEVSU-2287)] - new template can't be created with only one section
[[DEVSU-2288](https://www.bcgsc.ca/jira/browse/DEVSU-2288)] - dropdown menu for therapeutic targets starts at 3 letters, genes start at 2
[[DEVSU-2297](https://www.bcgsc.ca/jira/browse/DEVSU-2297)] - edit user pop-up in client is awkward/buggy
[[DEVSU-2299](https://www.bcgsc.ca/jira/browse/DEVSU-2299)] - in projects view, page info is cut off
[[DEVSU-2306](https://www.bcgsc.ca/jira/browse/DEVSU-2306)] - admins should see all projects in projects view
[[DEVSU-2325](https://www.bcgsc.ca/jira/browse/DEVSU-2325)] - Underline Not Working in Appendix Text
[[DEVSU-2351](https://www.bcgsc.ca/jira/browse/DEVSU-2351)] - make captiv-8 field editable in the genomic report
[[DEVSU-2352](https://www.bcgsc.ca/jira/browse/DEVSU-2352)] - appendix text loading to report summary display is broken
[[DEVSU-2353](https://www.bcgsc.ca/jira/browse/DEVSU-2353)] - Reordering TO table does not work as intended
[[DEVSU-2355](https://www.bcgsc.ca/jira/browse/DEVSU-2355)] - variant/cancer type values don't get set to null after variant text is created
[[DEVSU-2367](https://www.bcgsc.ca/jira/browse/DEVSU-2367)] - bullet points missing from analyst comments field
[[DEVSU-2369](https://www.bcgsc.ca/jira/browse/DEVSU-2369)] - remove option to add clinical trial rows to PTO tables
[[DEVSU-2375](https://www.bcgsc.ca/jira/browse/DEVSU-2375)] - Make paragraph element show spacing even if empty
[[DEVSU-2376](https://www.bcgsc.ca/jira/browse/DEVSU-2376)] - dropdown filter on column doesn't work on second page
[[DEVSU-2377](https://www.bcgsc.ca/jira/browse/DEVSU-2377)] - TumourSummary edit is missing a list of props
[[DEVSU-2383](https://www.bcgsc.ca/jira/browse/DEVSU-2383)] - Allow managers to edit appendices without specific projects
[[DEVSU-2390](https://www.bcgsc.ca/jira/browse/DEVSU-2390)] - error when sending test email
[[DEVSU-2392](https://www.bcgsc.ca/jira/browse/DEVSU-2392)] - handle null values for recruitment status
[[DEVSU-2393](https://www.bcgsc.ca/jira/browse/DEVSU-2393)] - NaN for PanGen report count in projects view
[[DEVSU-2394](https://www.bcgsc.ca/jira/browse/DEVSU-2394)] - bug with admin user project access
[[DEVSU-2396](https://www.bcgsc.ca/jira/browse/DEVSU-2396)] - TumourSummaryEdit fix for Genomic and Rapid
[[DEVSU-2398](https://www.bcgsc.ca/jira/browse/DEVSU-2398)] - update rapid report to get patho tc from sampleInfo not reportSampleInfo
[[DEVSU-2399](https://www.bcgsc.ca/jira/browse/DEVSU-2399)] - fix report-sample-info acquisition for report types in client
[[DEVSU-2401](https://www.bcgsc.ca/jira/browse/DEVSU-2401)] - report assignment access users can't assign reports
[[DEVSU-2402](https://www.bcgsc.ca/jira/browse/DEVSU-2402)] - 'group edited' message when group editing failed
[[DEVSU-2405](https://www.bcgsc.ca/jira/browse/DEVSU-2405)] - threshold for keyvariant search isn't making it to the search url correctly

**New Features**
[[DEVSU-1028](https://www.bcgsc.ca/jira/browse/DEVSU-1028)] - Aggregating therapeutic options table gene variant information
[[DEVSU-2138](https://www.bcgsc.ca/jira/browse/DEVSU-2138)] - Hyperlink POGs in correlation page
[[DEVSU-2247](https://www.bcgsc.ca/jira/browse/DEVSU-2247)] - add filter by variant to reports
[[DEVSU-2278](https://www.bcgsc.ca/jira/browse/DEVSU-2278)] - update appendix editing in client
[[DEVSU-2300](https://www.bcgsc.ca/jira/browse/DEVSU-2300)] - 'copy user permissions' feature for client
[[DEVSU-2336](https://www.bcgsc.ca/jira/browse/DEVSU-2336)] - add frontend for setting/displaying variant text
[[DEVSU-2337](https://www.bcgsc.ca/jira/browse/DEVSU-2337)] - edit client handling of sample info, if necessary

**Tasks**
[[DEVSU-2099](https://www.bcgsc.ca/jira/browse/DEVSU-2099)] - update potential therapeutic targets table to include signature
[[DEVSU-2161](https://www.bcgsc.ca/jira/browse/DEVSU-2161)] - display name of user who created the report, somewhere
[[DEVSU-2163](https://www.bcgsc.ca/jira/browse/DEVSU-2163)] - when report status is 'archived', don't allow any changes except to status
[[DEVSU-2257](https://www.bcgsc.ca/jira/browse/DEVSU-2257)] - add button to send test notification email to client
[[DEVSU-2267](https://www.bcgsc.ca/jira/browse/DEVSU-2267)] - remove 'beta' print option for non-genomic report types; rename option
[[DEVSU-2275](https://www.bcgsc.ca/jira/browse/DEVSU-2275)] - create separate summary types for genomic and rapid types
[[DEVSU-2281](https://www.bcgsc.ca/jira/browse/DEVSU-2281)] - add info to analysis status section
[[DEVSU-2290](https://www.bcgsc.ca/jira/browse/DEVSU-2290)] - Enable 'Add to Therapeutic Targets' Options for KB Matches
[[DEVSU-2298](https://www.bcgsc.ca/jira/browse/DEVSU-2298)] - fix groups view add/delete user
[[DEVSU-2301](https://www.bcgsc.ca/jira/browse/DEVSU-2301)] - 'my reports' filter
[[DEVSU-2321](https://www.bcgsc.ca/jira/browse/DEVSU-2321)] - review types in ipr-client - make sure no duplicates
[[DEVSU-2346](https://www.bcgsc.ca/jira/browse/DEVSU-2346)] - change potential-chemoresistance tablename to 'potential resistance and toxicity'

**Improvements**
[[DEVSU-1964](https://www.bcgsc.ca/jira/browse/DEVSU-1964)] - decrease whitespace in reports
[[DEVSU-2119](https://www.bcgsc.ca/jira/browse/DEVSU-2119)] - print report header contents update
[[DEVSU-2269](https://www.bcgsc.ca/jira/browse/DEVSU-2269)] - fix how user groups are handled
[[DEVSU-2271](https://www.bcgsc.ca/jira/browse/DEVSU-2271)] - implement condensed view for other report types
[[DEVSU-2272](https://www.bcgsc.ca/jira/browse/DEVSU-2272)] - remove the ability to edit template appendix texts on reports
[[DEVSU-2302](https://www.bcgsc.ca/jira/browse/DEVSU-2302)] - minor appendixview visual changes
[[DEVSU-2303](https://www.bcgsc.ca/jira/browse/DEVSU-2303)] - in AppendixView, display only first 10 or so lines of the appendix text
[[DEVSU-2304](https://www.bcgsc.ca/jira/browse/DEVSU-2304)] - add user-group descriptions
[[DEVSU-2305](https://www.bcgsc.ca/jira/browse/DEVSU-2305)] - less minor appendixview visual changes
[[DEVSU-2308](https://www.bcgsc.ca/jira/browse/DEVSU-2308)] - make it possible for users to view their own groups and projects
[[DEVSU-2312](https://www.bcgsc.ca/jira/browse/DEVSU-2312)] - add delete/create for appendix text
[[DEVSU-2313](https://www.bcgsc.ca/jira/browse/DEVSU-2313)] - add reviewer and creator columns to reports view
[[DEVSU-2319](https://www.bcgsc.ca/jira/browse/DEVSU-2319)] - use tooltips for viewing contents of cells with long string data
[[DEVSU-2333](https://www.bcgsc.ca/jira/browse/DEVSU-2333)] - move biopsy collection date up to the patient/tumour summary in the client
[[DEVSU-2334](https://www.bcgsc.ca/jira/browse/DEVSU-2334)] - add biopsy_type field to report view
[[DEVSU-2342](https://www.bcgsc.ca/jira/browse/DEVSU-2342)] - Reactivate PatientsView in IPR
[[DEVSU-2360](https://www.bcgsc.ca/jira/browse/DEVSU-2360)] - convert variant-text cancer-type field to a list
[[DEVSU-2362](https://www.bcgsc.ca/jira/browse/DEVSU-2362)] - changes to microbial status field handling in client
[[DEVSU-2371](https://www.bcgsc.ca/jira/browse/DEVSU-2371)] - Allow editing of Cancer Type on variant text
[[DEVSU-2389](https://www.bcgsc.ca/jira/browse/DEVSU-2389)] - update display of lists of objects in DetailView

**Non-tickets**
[bugfix/add-remaining-group-descriptions](https://github.com/bcgsc/pori_ipr_client/commit/4d6212cb2576dadb57a9f6cf06da239bf1ae5db2) - add three remaining groups to displayed groups
[bugfix/remove-reportsview-biopsytype-column](https://github.com/bcgsc/pori_ipr_client/commit/931baedac630399c912b1bd3b134c8b19814bdcf) - remove column not wanted by clininfo

### CODE REVIEW

**Comment by kttkjl** [comment]
TODO: add DEVSU 2371 2367 2369 to this release

**Comment by bnguyen-bcgsc** [comment]
Reminder, add these to the release PR:
- [[DEVSU-2399](https://www.bcgsc.ca/jira/browse/DEVSU-2399)]
- [[DEVSU-2389](https://www.bcgsc.ca/jira/browse/DEVSU-2389)]
- [[DEVSU-2398](https://www.bcgsc.ca/jira/browse/DEVSU-2398)]
- [[DEVSU-2386](https://www.bcgsc.ca/jira/browse/DEVSU-2386)]
- [[DEVSU-2247](https://www.bcgsc.ca/jira/browse/DEVSU-2247)]
- https://github.com/bcgsc/pori_ipr_client/pull/536#pullrequestreview-2200506730

**Comment by bnguyen-bcgsc** [comment]
Reminder to add DEVSU-2401 to release PR after merging to dev

**Comment by kttkjl** [comment]
[[DEVSU-2386](https://www.bcgsc.ca/jira/browse/DEVSU-2386)] is an API ticket, not in this list

**Review by elewis2 — APPROVED** [review]

**Pull request merged**
